### ISSUE TITLE
Docker命令运行报错

### ISSUE THREAD

**Issue by 17huiwei** [catlair/BiliTools#43]
root@localhost:/web/BiliTools# docker run -v $(pwd)/config:/usr/src/app/config -i --rm  catlair/bilitools:latest
version=0.3.20
没有可以转化的内容
未找到配置文件 Error: Cannot find module '../config/config.temp.json'
Require stack:
- /usr/src/app/tools/cfgCompatibility.js
- /usr/src/app/tools/bootstrap.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at module.exports (/usr/src/app/tools/cfgCompatibility.js:13:14)
    at Object.<anonymous> (/usr/src/app/tools/bootstrap.js:6:43)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/src/app/tools/cfgCompatibility.js',
    '/usr/src/app/tools/bootstrap.js'
  ]
}

**Comment by KudouRan** [comment]
如报错所见，你没有提供正确的配置
`$(pwd)/config` 指当前目录下的 `config` 目录，请检查该目录是否存在
